#+TITLE: Review 1337777.OOO solution programme : Maclane pentagon is some recursive square
#+AUTHOR: Christopher Mary
#+OPTIONS: date:nil email:nil timestamp:nil toc:nil
#+LATEX_CLASS: llncs
#+LATEX_HEADER: \institute{1337777.OOO}
#+LATEX_HEADER: \titlerunning{Review 1337777.OOO solution programme}

#+BEGIN_SRC emacs-lisp :cache yes :exports results :results silent
  (add-to-list 'org-latex-classes
  '("llncs" "\\documentclass[runningheads,a4paper]{llncs}" ("\\section{%s}"
  . "\\section*{%s}") ("\\subsection{%s}"
  . "\\subsection*{%s}") ("\\subsubsection{%s}"
  . "\\subsubsection*{%s}") ("\\paragraph{%s}"
  . "\\paragraph*{%s}") ("\\subparagraph{%s}"
  . "\\subparagraph*{%s}")))
#+END_SRC

#+LATEX: \begin{abstract}
This memo presents that some random-moment new angle of view, that
Maclane pentagon is some recursive square, onto some decades-old
question may solve some common falsification in mathematics. Moreover
the computational logical content of this new angle of view is
programmed into the COQ computer « 1337777.OOO//coherence2.v » . En
passant, this memo confirms that the only real mathematical research
or industry is the « engineering » of some computational-logical
software with varying degree of embedded logicalness, and everything
else is the education or teaching of « ideas » .
#+LATEX: \keywords{associative coherence ; Maclane ; angle of view}
#+LATEX: \end{abstract}

* Outline

  This memo presents some new lemma, that Maclane pentagon is some
recursive square, which is held in the real deduction of the Maclane
associative coherence, because Maclane's old deduction-attempt is not
the reality. Moreover the computational logical content of this
random-moment new angle of view is programmed into the COQ computer «
google.com/#q=1337777.OOO//coherence2.v » . This lemma constructs some
adjunction functor from the associative category of words-objects and
bracketing-arrows to the semiassociative (oriented bracketing-arrows)
category. Elsewhere this associative coherence is the meta for the
completeness lemma of another semiassociative coherence which does
lack some more-common Newman-style confluence lemma.

  One common way to automatically obtain any adjunction functor is to
start by giving the unit of the adjunction (here the normalization of
words) and by giving the universality-map of this unit of the
adjunction. This new angle of view is that the Maclane pentagon is
precisely one such given half of this universality-map, but it is
sufficient.  As shown in this view :

#+LATEX: \begin{figure}\centering \includegraphics[scale=0.5]{maclaneSolution.svg.pdf} \caption{View}\end{figure}
#+HTML: <object type="image/svg+xml" data="./maclaneSolution.svg.svg" class="org-svg">
